// <auto-generated />
using System;
using Manzili;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manzili.Migrations
{
    [DbContext(typeof(ManziliDbContext))]
    [Migration("20251112014455_AddUserDataSeeding")]
    partial class AddUserDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Manzili.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Government")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Manzili.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("BlockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@gmail.com",
                            FullName = "Ahmed Hassan",
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOSomiuxubMBJd0b5zXoknncaNtP/RAQaI0WXKeFr/Y6IUj0KtkekAaIVBcXuCVKcw==",
                            PhoneNumber = "01012345678",
                            Role = "Buyer",
                            UpdatedAt = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam.adel@yahoo.com",
                            FullName = "Mariam Adel",
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEI6LEv2N2bN7hLwOk4bNssWmJWtVtsxmLTVbV7BfjhP9edO+HeZpT8/uP5nJaL0Zuw==",
                            PhoneNumber = "01098765432",
                            Role = "Provider",
                            UpdatedAt = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omarkhaled@outlook.com",
                            FullName = "Omar Khaled",
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJgr4+Tct67j8lvvaKSFativH7UxHpBNTqqiKXYbGu38c3rnoyYVY95FKKK7Xak/qw==",
                            PhoneNumber = "01029305160",
                            Role = "Buyer",
                            UpdatedAt = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.nabil@gmail.com",
                            FullName = "Sarah Nabil",
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELYaREqWkrIFh6BXmAArd01j3bX0u9t9vzcNNYbrYcWPOeDjh426NzplDJODTAELBw==",
                            PhoneNumber = "01022223333",
                            Role = "Provider",
                            UpdatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef.m@gmail.com",
                            FullName = "Youssef Mahmoud",
                            IsBlocked = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEBWwjjjUJO352Z7FseYUi1iJRsrh0c7uTS7rjfyEimExmhH+z8wXSK+oqenCPoClKw==",
                            PhoneNumber = "01044445555",
                            Role = "Provider",
                            UpdatedAt = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila.samir@icloud.com",
                            FullName = "Laila Samir",
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELYFzPVNGLj6Pxk1hHPP9twcePfSf9lov8Qzg/SVG2a4Hkg6ryXquePXtWdmWKzzRg==",
                            PhoneNumber = "01055556666",
                            Role = "Buyer",
                            UpdatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Manzili.Models.Address", b =>
                {
                    b.HasOne("Manzili.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Manzili.Models.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
